### ISSUE TITLE
Error in Logger

### ISSUE THREAD

**Issue by aweiand** [paranormal/blooper#2]
Hi!  I've got an error in _squid.cache_ , after hours debugging (seriusly, I'm not familiar with squid flow), I'we found a problem in _blooper.rb_ , with need this fix in top of the file: 
```
require 'logger' 
require 'logger-application' unless defined?(Logger::Application)
```

**Comment by paranormal** [comment]
Hi.

Ruby has changed it's std packaging some time ago, blooper must be fixed accordingly. I'm sorry that it caused you unnecessary problems and time waste.

Could you please submit your suggestion for change in for of merge request?
